crab submit -c ./ssww_crab_script/DYJetsToLL_M-10to50_cfg.py
crab submit -c ./ssww_crab_script/DYJetsToLL_M-10to50_ext1_cfg.py
crab submit -c ./ssww_crab_script/DYJetsToLL_M-50_ext2_cfg.py
crab submit -c ./ssww_crab_script/EWK_WW_cfg.py
crab submit -c ./ssww_crab_script/EWK_WZTo2L2Q_cfg.py
crab submit -c ./ssww_crab_script/EWK_WZ_4To60_cfg.py
crab submit -c ./ssww_crab_script/EWK_WZ_cfg.py
crab submit -c ./ssww_crab_script/EWK_ZZ_cfg.py
crab submit -c ./ssww_crab_script/GluGluWWTo2L2Nu_MCFM_cfg.py
crab submit -c ./ssww_crab_script/GluGluZZTo2E2Nu_MCFM_cfg.py
crab submit -c ./ssww_crab_script/GluGluZZTo2Mu2Nu_MCFM_cfg.py
crab submit -c ./ssww_crab_script/QCD_WW_cfg.py
crab submit -c ./ssww_crab_script/QCD_WZ0j_4To50_cfg.py
crab submit -c ./ssww_crab_script/QCD_WZ0j_cfg.py
crab submit -c ./ssww_crab_script/QCD_WZ1j_cfg.py
crab submit -c ./ssww_crab_script/QCD_WZ2j_4To50_cfg.py
crab submit -c ./ssww_crab_script/QCD_WZ2j_cfg.py
crab submit -c ./ssww_crab_script/QCD_WZ3j_4To50_cfg.py
crab submit -c ./ssww_crab_script/QCD_WZ3j_cfg.py
crab submit -c ./ssww_crab_script/QCD_ZZ_cfg.py
crab submit -c ./ssww_crab_script/ST_tW_antitop_cfg.py
crab submit -c ./ssww_crab_script/ST_tW_antitop_v2_cfg.py
crab submit -c ./ssww_crab_script/ST_tW_top_cfg.py
crab submit -c ./ssww_crab_script/ST_tW_top_v2_cfg.py
crab submit -c ./ssww_crab_script/TTTo2L2Nu_cfg.py
crab submit -c ./ssww_crab_script/TTWJetsToLNu_cfg.py
crab submit -c ./ssww_crab_script/TTWJetsToQQ_cfg.py
crab submit -c ./ssww_crab_script/TTZToLLNuNu_M-10_ext2_cfg.py
crab submit -c ./ssww_crab_script/TTZToLLNuNu_M-10_ext3_cfg.py
crab submit -c ./ssww_crab_script/TTZToQQ_cfg.py
crab submit -c ./ssww_crab_script/TT_TuneCUETP8M2T4_cfg.py
crab submit -c ./ssww_crab_script/WGJJToLNu_EWK_QCD_cfg.py
crab submit -c ./ssww_crab_script/WWJJToLNuLNu_EWK_noTop_cfg.py
crab submit -c ./ssww_crab_script/WWTo2L2Nu_DoubleScattering_cfg.py
crab submit -c ./ssww_crab_script/WWTo2L2Nu_cfg.py
crab submit -c ./ssww_crab_script/WWW_cfg.py
crab submit -c ./ssww_crab_script/WWZ_cfg.py
crab submit -c ./ssww_crab_script/WZZ_cfg.py
crab submit -c ./ssww_crab_script/WmWmJJ_cfg.py
crab submit -c ./ssww_crab_script/ZZTo2L2Nu_cfg.py
crab submit -c ./ssww_crab_script/ZZTo2L2Q_cfg.py
crab submit -c ./ssww_crab_script/ZZZ_cfg.py
crab submit -c ./ssww_crab_script/SingleElectron_B_cfg.py
crab submit -c ./ssww_crab_script/SingleElectron_C_cfg.py
crab submit -c ./ssww_crab_script/SingleElectron_D_cfg.py
crab submit -c ./ssww_crab_script/SingleElectron_E_cfg.py
crab submit -c ./ssww_crab_script/SingleElectron_F_cfg.py
crab submit -c ./ssww_crab_script/SingleElectron_G_cfg.py
crab submit -c ./ssww_crab_script/SingleElectron_H_cfg.py
crab submit -c ./ssww_crab_script/SingleMuon_B_cfg.py
crab submit -c ./ssww_crab_script/SingleMuon_C_cfg.py
crab submit -c ./ssww_crab_script/SingleMuon_D_cfg.py
crab submit -c ./ssww_crab_script/SingleMuon_E_cfg.py
crab submit -c ./ssww_crab_script/SingleMuon_F_cfg.py
crab submit -c ./ssww_crab_script/SingleMuon_G_cfg.py
crab submit -c ./ssww_crab_script/SingleMuon_H_cfg.py
crab submit -c ./ssww_crab_script/DoubleEG_B_cfg.py
crab submit -c ./ssww_crab_script/DoubleEG_C_cfg.py
crab submit -c ./ssww_crab_script/DoubleEG_D_cfg.py
crab submit -c ./ssww_crab_script/DoubleEG_E_cfg.py
crab submit -c ./ssww_crab_script/DoubleEG_F_cfg.py
crab submit -c ./ssww_crab_script/DoubleEG_G_cfg.py
crab submit -c ./ssww_crab_script/DoubleEG_H_cfg.py
crab submit -c ./ssww_crab_script/DoubleMuon_B_cfg.py
crab submit -c ./ssww_crab_script/DoubleMuon_C_cfg.py
crab submit -c ./ssww_crab_script/DoubleMuon_D_cfg.py
crab submit -c ./ssww_crab_script/DoubleMuon_E_cfg.py
crab submit -c ./ssww_crab_script/DoubleMuon_F_cfg.py
crab submit -c ./ssww_crab_script/DoubleMuon_G_cfg.py
crab submit -c ./ssww_crab_script/DoubleMuon_H_cfg.py
crab submit -c ./ssww_crab_script/MuonEG_B_cfg.py
crab submit -c ./ssww_crab_script/MuonEG_C_cfg.py
crab submit -c ./ssww_crab_script/MuonEG_D_cfg.py
crab submit -c ./ssww_crab_script/MuonEG_E_cfg.py
crab submit -c ./ssww_crab_script/MuonEG_F_cfg.py
crab submit -c ./ssww_crab_script/MuonEG_G_cfg.py
crab submit -c ./ssww_crab_script/MuonEG_H_cfg.py

#__CP5_WGJJToLNu_EWK_QCD_cfg.py
#__QCD_WZ1j_4To50_cfg.py
#__TTTo2L2Nu_cfg.py
#__WW_DoubleScattering_cfg.py
