crab kill -d crab_DYJetsToLL_M-10to50
crab kill -d crab_DYJetsToLL_M-10to50_ext1
crab kill -d crab_DYJetsToLL_M-50_ext2
crab kill -d crab_EWK_WW
crab kill -d crab_EWK_WZTo2L2Q
crab kill -d crab_EWK_WZ_4To60
crab kill -d crab_EWK_WZ
crab kill -d crab_EWK_ZZ
crab kill -d crab_GluGluWWTo2L2Nu_MCFM
crab kill -d crab_GluGluZZTo2E2Nu_MCFM
crab kill -d crab_GluGluZZTo2Mu2Nu_MCFM
crab kill -d crab_QCD_WW
crab kill -d crab_QCD_WZ0j_4To50
crab kill -d crab_QCD_WZ0j
crab kill -d crab_QCD_WZ1j
crab kill -d crab_QCD_WZ2j_4To50
crab kill -d crab_QCD_WZ2j
crab kill -d crab_QCD_WZ3j_4To50
crab kill -d crab_QCD_WZ3j
crab kill -d crab_QCD_ZZ
crab kill -d crab_ST_tW_antitop
crab kill -d crab_ST_tW_antitop_v2
crab kill -d crab_ST_tW_top
crab kill -d crab_ST_tW_top_v2
crab kill -d crab_TTTo2L2Nu
crab kill -d crab_TTWJetsToLNu
crab kill -d crab_TTWJetsToQQ
crab kill -d crab_TTZToLLNuNu_M-10_ext2
crab kill -d crab_TTZToLLNuNu_M-10_ext3
crab kill -d crab_TTZToQQ
crab kill -d crab_TT_TuneCUETP8M2T4
crab kill -d crab_WGJJToLNu_EWK_QCD
crab kill -d crab_WWJJToLNuLNu_EWK_noTop
crab kill -d crab_WWTo2L2Nu_DoubleScattering
crab kill -d crab_WWTo2L2Nu
crab kill -d crab_WWW
crab kill -d crab_WWZ
crab kill -d crab_WZZ
crab kill -d crab_WmWmJJ
crab kill -d crab_ZZTo2L2Nu
crab kill -d crab_ZZTo2L2Q
crab kill -d crab_ZZZ
crab kill -d crab_SingleElectron_B
crab kill -d crab_SingleElectron_C
crab kill -d crab_SingleElectron_D
crab kill -d crab_SingleElectron_E
crab kill -d crab_SingleElectron_F
crab kill -d crab_SingleElectron_G
crab kill -d crab_SingleElectron_H
crab kill -d crab_SingleMuon_B
crab kill -d crab_SingleMuon_C
crab kill -d crab_SingleMuon_D
crab kill -d crab_SingleMuon_E
crab kill -d crab_SingleMuon_F
crab kill -d crab_SingleMuon_G
crab kill -d crab_SingleMuon_H
crab kill -d crab_DoubleEG_B
crab kill -d crab_DoubleEG_C
crab kill -d crab_DoubleEG_D
crab kill -d crab_DoubleEG_E
crab kill -d crab_DoubleEG_F
crab kill -d crab_DoubleEG_G
crab kill -d crab_DoubleEG_H
crab kill -d crab_DoubleMuon_B
crab kill -d crab_DoubleMuon_C
crab kill -d crab_DoubleMuon_D
crab kill -d crab_DoubleMuon_E
crab kill -d crab_DoubleMuon_F
crab kill -d crab_DoubleMuon_G
crab kill -d crab_DoubleMuon_H1
crab kill -d crab_MuonEG_B
crab kill -d crab_MuonEG_C
crab kill -d crab_MuonEG_D
crab kill -d crab_MuonEG_E
crab kill -d crab_MuonEG_F
crab kill -d crab_MuonEG_G
crab kill -d crab_MuonEG_H
#__CP5_WGJJToLNu_EWK_QCD
#__QCD_WZ1j_4To50
#__TTTo2L2Nu
#__WW_DoubleScattering
