crab submit -c ./ssww_loose_crab_script/loose_DYJetsToLL_M-10to50_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DYJetsToLL_M-10to50_ext1_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DYJetsToLL_M-50_ext2_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_EWK_WW_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_EWK_WZTo2L2Q_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_EWK_WZ_4To60_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_EWK_WZ_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_EWK_ZZ_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_GluGluWWTo2L2Nu_MCFM_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_GluGluZZTo2E2Nu_MCFM_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_GluGluZZTo2Mu2Nu_MCFM_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_QCD_WW_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_QCD_WZ0j_4To50_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_QCD_WZ0j_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_QCD_WZ1j_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_QCD_WZ2j_4To50_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_QCD_WZ2j_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_QCD_WZ3j_4To50_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_QCD_WZ3j_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_QCD_ZZ_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_ST_tW_antitop_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_ST_tW_antitop_v2_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_ST_tW_top_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_ST_tW_top_v2_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_TTTo2L2Nu_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_TTWJetsToLNu_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_TTWJetsToQQ_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_TTZToLLNuNu_M-10_ext2_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_TTZToLLNuNu_M-10_ext3_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_TTZToQQ_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_TT_TuneCUETP8M2T4_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_WGJJToLNu_EWK_QCD_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_WWJJToLNuLNu_EWK_noTop_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_WWTo2L2Nu_DoubleScattering_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_WWTo2L2Nu_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_WWW_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_WWZ_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_WZZ_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_WmWmJJ_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_ZZTo2L2Nu_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_ZZTo2L2Q_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_ZZZ_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleElectron_B_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleElectron_C_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleElectron_D_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleElectron_E_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleElectron_F_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleElectron_G_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleElectron_H_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleMuon_B_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleMuon_C_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleMuon_D_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleMuon_E_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleMuon_F_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleMuon_G_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_SingleMuon_H_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleEG_B_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleEG_C_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleEG_D_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleEG_E_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleEG_F_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleEG_G_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleEG_H_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleMuon_B_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleMuon_C_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleMuon_D_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleMuon_E_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleMuon_F_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleMuon_G_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_DoubleMuon_H_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_MuonEG_B_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_MuonEG_C_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_MuonEG_D_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_MuonEG_E_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_MuonEG_F_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_MuonEG_G_cfg.py
crab submit -c ./ssww_loose_crab_script/loose_MuonEG_H_cfg.py

#__CP5_WGJJToLNu_EWK_QCD_cfg.py
#__QCD_WZ1j_4To50_cfg.py
#__TTTo2L2Nu_cfg.py
#__WW_DoubleScattering_cfg.py
