crab status -d crab_loose_DYJetsToLL_M-10to50
crab status -d crab_loose_DYJetsToLL_M-10to50_ext1
crab status -d crab_loose_DYJetsToLL_M-50_ext2
crab status -d crab_loose_EWK_WW
crab status -d crab_loose_EWK_WZTo2L2Q
crab status -d crab_loose_EWK_WZ_4To60
crab status -d crab_loose_EWK_WZ
crab status -d crab_loose_EWK_ZZ
crab status -d crab_loose_GluGluWWTo2L2Nu_MCFM
crab status -d crab_loose_GluGluZZTo2E2Nu_MCFM
crab status -d crab_loose_GluGluZZTo2Mu2Nu_MCFM
crab status -d crab_loose_QCD_WW
crab status -d crab_loose_QCD_WZ0j_4To50
crab status -d crab_loose_QCD_WZ0j
crab status -d crab_loose_QCD_WZ1j
crab status -d crab_loose_QCD_WZ2j_4To50
crab status -d crab_loose_QCD_WZ2j
crab status -d crab_loose_QCD_WZ3j_4To50
crab status -d crab_loose_QCD_WZ3j
crab status -d crab_loose_QCD_ZZ
crab status -d crab_loose_ST_tW_antitop
crab status -d crab_loose_ST_tW_antitop_v2
crab status -d crab_loose_ST_tW_top
crab status -d crab_loose_ST_tW_top_v2
crab status -d crab_loose_TTTo2L2Nu
crab status -d crab_loose_TTWJetsToLNu
crab status -d crab_loose_TTWJetsToQQ
crab status -d crab_loose_TTZToLLNuNu_M-10_ext2
crab status -d crab_loose_TTZToLLNuNu_M-10_ext3
crab status -d crab_loose_TTZToQQ
crab status -d crab_loose_TT_TuneCUETP8M2T4
crab status -d crab_loose_WGJJToLNu_EWK_QCD
crab status -d crab_loose_WWJJToLNuLNu_EWK_noTop
crab status -d crab_loose_WWTo2L2Nu_DoubleScattering
crab status -d crab_loose_WWTo2L2Nu
crab status -d crab_loose_WWW
crab status -d crab_loose_WWZ
crab status -d crab_loose_WZZ
crab status -d crab_loose_WmWmJJ
crab status -d crab_loose_ZZTo2L2Nu
crab status -d crab_loose_ZZTo2L2Q
crab status -d crab_loose_ZZZ
crab status -d crab_loose_SingleElectron_B
crab status -d crab_loose_SingleElectron_C
crab status -d crab_loose_SingleElectron_D
crab status -d crab_loose_SingleElectron_E
crab status -d crab_loose_SingleElectron_F
crab status -d crab_loose_SingleElectron_G
crab status -d crab_loose_SingleElectron_H
crab status -d crab_loose_SingleMuon_B
crab status -d crab_loose_SingleMuon_C
crab status -d crab_loose_SingleMuon_D
crab status -d crab_loose_SingleMuon_E
crab status -d crab_loose_SingleMuon_F
crab status -d crab_loose_SingleMuon_G
crab status -d crab_loose_SingleMuon_H
crab status -d crab_loose_DoubleEG_B
crab status -d crab_loose_DoubleEG_C
crab status -d crab_loose_DoubleEG_D
crab status -d crab_loose_DoubleEG_E
crab status -d crab_loose_DoubleEG_F
crab status -d crab_loose_DoubleEG_G
crab status -d crab_loose_DoubleEG_H
crab status -d crab_loose_DoubleMuon_B
crab status -d crab_loose_DoubleMuon_C
crab status -d crab_loose_DoubleMuon_D
crab status -d crab_loose_DoubleMuon_E
crab status -d crab_loose_DoubleMuon_F
crab status -d crab_loose_DoubleMuon_G
crab status -d crab_loose_DoubleMuon_H
crab status -d crab_loose_MuonEG_B
crab status -d crab_loose_MuonEG_C
crab status -d crab_loose_MuonEG_D
crab status -d crab_loose_MuonEG_E
crab status -d crab_loose_MuonEG_F
crab status -d crab_loose_MuonEG_G
crab status -d crab_loose_MuonEG_H
#__CP5_WGJJToLNu_EWK_QCD
#__QCD_WZ1j_4To50
#__TTTo2L2Nu
#__WW_DoubleScattering
